name: flutter_assignments
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  collection: ^1.19.1
  provider: ^6.0.5
  get_it: ^7.2.0
  dio: ^5.1.1
  json_annotation: 4.9.0
  dropdown_button2: ^2.3.9
  freezed_annotation: 2.4.4
  shared_preferences: ^2.2.0
  firebase_core: ^2.12.0
  firebase_messaging: ^14.2.6
  flutter_local_notifications: ^18.0.1
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  table_calendar: ^3.2.0
  intl:
  flutter_svg: ^2.0.17
  flutter_dotenv: ^5.2.1
  sembast:
  flutter_dialogs:

dev_dependencies:
  build_runner: 2.4.14
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: 2.5.7
  json_serializable: 6.9.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
